version: "3.8"

networks:
  appointments-tests-network:
    name: appointments-tests-network

services:

  mongo:
    image: mongo:6.0.5
    ports:
      - 27017:27017
    networks:
      - appointments-tests-network
  
  redis:
    image: redis:6.2.0-alpine
    ports:
      - 6379:6379
    networks:
      - appointments-tests-network

  rabbitmq:
    image: rabbitmq:3.12.12-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - appointments-tests-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
